### ISSUE TITLE
install_prerequisites.py fails with TabError

### ISSUE THREAD

**Issue by keithj** [irods/externals#18]
`4-2-stable`, RHEL 7.4

````
[cloud-user@kdj-build externals]$ ./install_prerequisites.py 
Traceback (most recent call last):
  File "./install_prerequisites.py", line 5, in <module>
    import build
  File "/home/cloud-user/miniconda/conda-bld/irods_1546964307816/work/externals/build.py", line 204
    if not os.path.isdir(os.path.join(build_dir,target)):
                                                        ^
TabError: inconsistent use of tabs and spaces in indentation
````

**Comment by trel** [comment]
pylint also shows other sins, one moment please.

**Comment by trel** [comment]
please reopen if you find another
