### ISSUE TITLE
building with docker on centos 7 failed

### ISSUE THREAD

**Issue by efflamlemaillet** [irods/externals#91]
I ran into this error while trying to build externals with docker : 
```
 RUN /bin/bash -c  'cd ${IRODS_EXT_PATH} && python ./install_prerequisites.py && make'
 ---> Running in c6b4f334e262
INFO - Detected: CentOS Linux
INFO - running: ['sudo', 'rpm', '--rebuilddb'], unsafe_shell=False, check_rc=rpm rebuild failed, retries=0
Traceback (most recent call last):
  File "./install_prerequisites.py", line 144, in <module>
    sys.exit(main())
  File "./install_prerequisites.py", line 105, in main
    build.run_cmd(cmd, check_rc='rpm rebuild failed')
  File "/externals/build.py", line 90, in run_cmd
    p = subprocess.Popen(cmd, env=run_env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
It seems to be a docker related error as similar commands pass on a vm 
any idea what make container error ?

$ docker -v
Docker version 19.03.9, build 9d988398e7
Dockerfile :
```
ARG CENTOS_VERSION=centos7.7.1908
FROM centos:${CENTOS_VERSION} as centos-dev-tools
ARG IRODS_EXT_GIT_REPO=https://github.com/irods/externals.git
ARG IRODS_EXT_BRANCH=4-2-stable
ARG IRODS_EXT_PATH=externals
RUN yum upgrade -y # did not help
RUN yum -y install git python
RUN git clone --depth=50 --single-branch --branch=${IRODS_EXT_BRANCH} ${IRODS_EXT_GIT_REPO} ${IRODS_EXT_PATH}
RUN /bin/bash -c  'cd ${IRODS_EXT_PATH} && python ./install_prerequisites.py && make'
CMD ["/bin/bash"]

```

**Comment by osallou** [comment]
Need to add sudo package

**Comment by efflamlemaillet** [comment]
Indeed i added sudo 
`RUN yum -y install git python sudo`
and command passed.
Maybe add a comment about it  in the README when building in container ?

**Comment by trel** [comment]
No worries.

```
# CentOS 7
yum install -y sudo git python
```
